[package]
name = "type_cosplay"
version = "0.1.0"
authors = ["authors go here"]
description = "decription goes here"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[[example]]
name = "insecure"
path = "ui/insecure/src/lib.rs"

[[example]]
name = "insecure-two"
path = "ui/insecure-two/src/lib.rs"

[[example]]
name = "insecure-three"
path = "ui/insecure-three/src/lib.rs"

[[example]]
name = "recommended"
path = "ui/recommended/src/lib.rs"

[[example]]
name = "secure"
path = "ui/secure/src/lib.rs"

[dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "b312ad7d0cf0f30be2bd4658b71a3520a2e76709" }
dylint_linting = "2.0.1"
if_chain = "1.0.2"
solana-lints = { path = "../../crate" }

[dev-dependencies]
dylint_testing = "2.0.1"
anchor-lang = "0.24.2"

[package.metadata.rust-analyzer]
rustc_private = true
